using System;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json.Nodes;
using System.Threading;
using System.Threading.Tasks;
using Emby.Server.Implementations;
using Emby.Server.Implementations.Serialization;
using Jellyfin.Database.Implementations;
using Jellyfin.Database.Implementations.Entities;
using Jellyfin.Database.Providers.PostgreSql;
using Jellyfin.Database.Providers.PostgreSql.Migrations;
using Jellyfin.Server.Migrations;
using Jellyfin.Server.Migrations.Routines;
using Jellyfin.Server.Migrations.Stages;
using Jellyfin.Server.ServerSetupApp;
using MediaBrowser.Model.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging.Abstractions;
using Moq;
using Xunit;

namespace Jellyfin.Server.Implementations.Tests.Data.PostgreSql;

[Collection(PostgreSqlIntegrationCollection.Name)]
public sealed class PostgreSqlMigrationTests
{
    private readonly PostgreSqlDatabaseFixture _fixture;

    public PostgreSqlMigrationTests(PostgreSqlDatabaseFixture fixture)
    {
        _fixture = fixture;
    }

    [Fact]
    public void MigrationAssembly_HasIndependentBaselineAndGeneratesIdempotentScript()
    {
        var factory = new PostgreSqlDesignTimeJellyfinDbFactory();
        using var context = factory.CreateDbContext([]);
        var baseline = Assert.Single(context.Database.GetMigrations());

        Assert.EndsWith("_InitialPostgreSqlBaseline", baseline, StringComparison.Ordinal);
        Assert.DoesNotContain("SQLite", baseline, StringComparison.OrdinalIgnoreCase);

        var script = context.GetService<IMigrator>().GenerateScript(
            Migration.InitialDatabase,
            baseline,
            MigrationsSqlGenerationOptions.Idempotent);

        Assert.Contains("CREATE TABLE IF NOT EXISTS \"__EFMigrationsHistory\"", script, StringComparison.Ordinal);
        Assert.Contains($"WHERE \"MigrationId\" = '{baseline}'", script, StringComparison.Ordinal);
        Assert.Contains("GENERATED BY DEFAULT AS IDENTITY", script, StringComparison.Ordinal);
        Assert.Contains("GENERATED ALWAYS AS (lower(\"Name\")) STORED", script, StringComparison.Ordinal);
        Assert.Contains("USING hash", script, StringComparison.Ordinal);
        Assert.DoesNotContain("PRAGMA", script, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public async Task MigrateAsync_AppliesBaselineOnceAndCanRunAgain()
    {
        Assert.SkipUnless(_fixture.IsConfigured, _fixture.SkipReason);
        var cancellationToken = TestContext.Current.CancellationToken;
        var database = await _fixture.GetDatabaseAsync(cancellationToken).ConfigureAwait(true);
        await database.ResetAsync(cancellationToken).ConfigureAwait(true);

        string baseline;
        await using (var context = database.CreateDbContext())
        {
            baseline = Assert.Single(context.Database.GetMigrations());
            await context.Database.MigrateAsync(cancellationToken).ConfigureAwait(true);

            Assert.Empty(await context.Database.GetPendingMigrationsAsync(cancellationToken).ConfigureAwait(true));
            Assert.Equal(new[] { baseline }, await context.Database.GetAppliedMigrationsAsync(cancellationToken).ConfigureAwait(true));
        }

        await using (var context = database.CreateDbContext())
        {
            await context.Database.MigrateAsync(cancellationToken).ConfigureAwait(true);

            Assert.Empty(await context.Database.GetPendingMigrationsAsync(cancellationToken).ConfigureAwait(true));
            Assert.Equal(new[] { baseline }, await context.Database.GetAppliedMigrationsAsync(cancellationToken).ConfigureAwait(true));
        }

        Assert.Equal(
            1,
            await database.ExecuteScalarAsync<long>(
                "SELECT count(*) FROM \"__EFMigrationsHistory\"",
                cancellationToken).ConfigureAwait(true));
    }

    [Fact]
    public async Task Startup_FreshPreCreatedDatabaseSeedsHistoryAndNormalRestartIsStable()
    {
        Assert.SkipUnless(_fixture.IsConfigured, _fixture.SkipReason);
        var cancellationToken = TestContext.Current.CancellationToken;
        var database = await _fixture.GetDatabaseAsync(cancellationToken).ConfigureAwait(true);
        await database.ResetAsync(cancellationToken).ConfigureAwait(true);
        var root = Path.Combine(Path.GetTempPath(), "jellyfin-postgresql-startup-tests", Guid.NewGuid().ToString("N"));
        var paths = new ServerApplicationPaths(
            Path.Combine(root, "data"),
            Path.Combine(root, "log"),
            Path.Combine(root, "config"),
            Path.Combine(root, "cache"),
            Path.Combine(root, "web"));
        Directory.CreateDirectory(paths.DataPath);
        Directory.CreateDirectory(paths.LogDirectoryPath);
        Directory.CreateDirectory(paths.ConfigurationDirectoryPath);
        Directory.CreateDirectory(paths.CachePath);

        try
        {
            new MyXmlSerializer().SerializeToFile(
                new ServerConfiguration { IsStartupWizardCompleted = false },
                paths.SystemConfigurationFilePath);
            var provider = new PostgreSqlDatabaseProvider(NullLogger<PostgreSqlDatabaseProvider>.Instance);
            var factory = new Mock<IDbContextFactory<JellyfinDbContext>>();
            factory
                .Setup(contextFactory => contextFactory.CreateDbContextAsync(It.IsAny<CancellationToken>()))
                .ReturnsAsync(database.CreateDbContext);
            var migrationService = new JellyfinMigrationService(
                factory.Object,
                NullLoggerFactory.Instance,
                new StartupLogger<JellyfinMigrationService>(NullLogger<JellyfinMigrationService>.Instance),
                paths,
                jellyfinDatabaseProvider: provider);
            using var services = new ServiceCollection().BuildServiceProvider();

            await migrationService.CheckFirstTimeRunOrMigration(paths, new StartupOptions()).ConfigureAwait(true);

            await using (var seededContext = database.CreateDbContext())
            {
                var seededMigrationIds = await seededContext.GetService<IHistoryRepository>()
                    .GetAppliedMigrationsAsync(cancellationToken)
                    .ConfigureAwait(true);
                Assert.Contains(seededMigrationIds, row => row.MigrationId.EndsWith("_StripEmbeddedLinkedChildren", StringComparison.Ordinal));
                Assert.DoesNotContain(seededMigrationIds, row => row.MigrationId.EndsWith("_InitialPostgreSqlBaseline", StringComparison.Ordinal));
            }

            await migrationService.PrepareSystemForMigration(NullLogger.Instance).ConfigureAwait(true);
            Assert.True(await migrationService.MigrateStepAsync(JellyfinMigrationStageTypes.CoreInitialisation, services).ConfigureAwait(true));

            string[] firstStartupHistory;
            await using (var migratedContext = database.CreateDbContext())
            {
                firstStartupHistory = (await migratedContext.GetService<IHistoryRepository>()
                        .GetAppliedMigrationsAsync(cancellationToken)
                        .ConfigureAwait(true))
                    .Select(row => row.MigrationId)
                    .Order(StringComparer.Ordinal)
                    .ToArray();
                Assert.Contains(firstStartupHistory, migrationId => migrationId.EndsWith("_InitialPostgreSqlBaseline", StringComparison.Ordinal));
            }

            new MyXmlSerializer().SerializeToFile(
                new ServerConfiguration { IsStartupWizardCompleted = true },
                paths.SystemConfigurationFilePath);
            await migrationService.CheckFirstTimeRunOrMigration(paths, new StartupOptions()).ConfigureAwait(true);
            Assert.False(await migrationService.MigrateStepAsync(JellyfinMigrationStageTypes.CoreInitialisation, services).ConfigureAwait(true));

            await using var restartedContext = database.CreateDbContext();
            Assert.Equal(
                firstStartupHistory,
                (await restartedContext.GetService<IHistoryRepository>()
                        .GetAppliedMigrationsAsync(cancellationToken)
                        .ConfigureAwait(true))
                    .Select(row => row.MigrationId)
                    .Order(StringComparer.Ordinal));
        }
        finally
        {
            Directory.Delete(root, true);
        }
    }

    [Theory]
    [InlineData(false)]
    [InlineData(true)]
    public async Task Startup_BaselineOrPartialCodeHistorySeedsEveryInapplicableMigrationWithoutExecutingThem(bool seedPartialCodeHistory)
    {
        Assert.SkipUnless(_fixture.IsConfigured, _fixture.SkipReason);
        var cancellationToken = TestContext.Current.CancellationToken;
        var database = await _fixture.GetDatabaseAsync(cancellationToken).ConfigureAwait(true);
        await database.ResetAsync(cancellationToken).ConfigureAwait(true);
        var markerId = Guid.NewGuid();
        const string MarkerData = "{\"Name\":\"unchanged\",\"LinkedChildren\":[1]}";
        var codeMigrations = typeof(JellyfinMigrationService).Assembly.GetTypes()
            .Select(type => (Type: type, Metadata: type.GetCustomAttributes(typeof(JellyfinMigrationAttribute), false)
                .Cast<JellyfinMigrationAttribute>()
                .SingleOrDefault()))
            .Where(item => item.Metadata is not null)
            .Select(item => (Id: new CodeMigration(item.Type, item.Metadata!, null).BuildCodeMigrationId(), item.Metadata!.RunMigrationOnSetup))
            .ToArray();
        var expectedSeededMigrationIds = codeMigrations
            .Where(item => !item.RunMigrationOnSetup)
            .Select(item => item.Id)
            .Order(StringComparer.Ordinal)
            .ToArray();

        await using (var context = database.CreateDbContext())
        {
            await context.Database.MigrateAsync(cancellationToken).ConfigureAwait(true);
            context.BaseItems.Add(new BaseItemEntity { Id = markerId, Type = "Movie", Data = MarkerData });
            await context.SaveChangesAsync(cancellationToken).ConfigureAwait(true);

            if (seedPartialCodeHistory)
            {
                var historyRepository = context.GetService<IHistoryRepository>();
                await context.Database.ExecuteSqlRawAsync(
                    historyRepository.GetInsertScript(new HistoryRow(expectedSeededMigrationIds[0], "test")),
                    cancellationToken).ConfigureAwait(true);
            }
        }

        var root = Path.Combine(Path.GetTempPath(), "jellyfin-postgresql-seed-history-tests", Guid.NewGuid().ToString("N"));
        var paths = CreateApplicationPaths(root);
        try
        {
            new MyXmlSerializer().SerializeToFile(
                new ServerConfiguration { IsStartupWizardCompleted = false },
                paths.SystemConfigurationFilePath);
            var provider = new PostgreSqlDatabaseProvider(NullLogger<PostgreSqlDatabaseProvider>.Instance);
            var factory = new Mock<IDbContextFactory<JellyfinDbContext>>();
            factory
                .Setup(contextFactory => contextFactory.CreateDbContextAsync(It.IsAny<CancellationToken>()))
                .ReturnsAsync(database.CreateDbContext);
            var migrationService = new JellyfinMigrationService(
                factory.Object,
                NullLoggerFactory.Instance,
                new StartupLogger<JellyfinMigrationService>(NullLogger<JellyfinMigrationService>.Instance),
                paths,
                jellyfinDatabaseProvider: provider);

            await migrationService.CheckFirstTimeRunOrMigration(paths, new StartupOptions()).ConfigureAwait(true);
            await migrationService.PrepareSystemForMigration(NullLogger.Instance).ConfigureAwait(true);
            using var services = new ServiceCollection().BuildServiceProvider();

            await using var verification = database.CreateDbContext();
            var appliedMigrationIds = (await verification.GetService<IHistoryRepository>()
                    .GetAppliedMigrationsAsync(cancellationToken)
                    .ConfigureAwait(true))
                .Select(row => row.MigrationId)
                .ToHashSet(StringComparer.Ordinal);
            Assert.All(expectedSeededMigrationIds, migrationId => Assert.Contains(migrationId, appliedMigrationIds));

            var historyRepository = verification.GetService<IHistoryRepository>();
            foreach (var setupMigrationId in codeMigrations.Where(item => item.RunMigrationOnSetup).Select(item => item.Id))
            {
                if (appliedMigrationIds.Add(setupMigrationId))
                {
                    await verification.Database.ExecuteSqlRawAsync(
                        historyRepository.GetInsertScript(new HistoryRow(setupMigrationId, "test")),
                        cancellationToken).ConfigureAwait(true);
                }
            }

            foreach (var stage in Enum.GetValues<JellyfinMigrationStageTypes>())
            {
                Assert.False(await migrationService.MigrateStepAsync(stage, services).ConfigureAwait(true));
            }

            Assert.Equal(
                MarkerData,
                (await verification.BaseItems.FindAsync([markerId], cancellationToken).ConfigureAwait(true))!.Data);
        }
        finally
        {
            Directory.Delete(root, true);
        }
    }

    [Fact]
    public async Task Startup_MissingPostgreSqlDatabaseFailsWithoutCreatingIt()
    {
        Assert.SkipUnless(_fixture.IsConfigured, _fixture.SkipReason);
        var cancellationToken = TestContext.Current.CancellationToken;
        var database = await _fixture.GetDatabaseAsync(cancellationToken).ConfigureAwait(true);
        var missingDatabaseName = PostgreSqlTestDatabase.CreateDatabaseName();
        var root = Path.Combine(Path.GetTempPath(), "jellyfin-postgresql-missing-database-tests", Guid.NewGuid().ToString("N"));
        var paths = new ServerApplicationPaths(
            Path.Combine(root, "data"),
            Path.Combine(root, "log"),
            Path.Combine(root, "config"),
            Path.Combine(root, "cache"),
            Path.Combine(root, "web"));
        Directory.CreateDirectory(paths.DataPath);
        Directory.CreateDirectory(paths.LogDirectoryPath);
        Directory.CreateDirectory(paths.ConfigurationDirectoryPath);
        Directory.CreateDirectory(paths.CachePath);

        try
        {
            new MyXmlSerializer().SerializeToFile(
                new ServerConfiguration { IsStartupWizardCompleted = false },
                paths.SystemConfigurationFilePath);
            var provider = new PostgreSqlDatabaseProvider(NullLogger<PostgreSqlDatabaseProvider>.Instance);
            var factory = new Mock<IDbContextFactory<JellyfinDbContext>>();
            factory
                .Setup(contextFactory => contextFactory.CreateDbContextAsync(It.IsAny<CancellationToken>()))
                .ReturnsAsync(() => database.CreateDbContextForDatabase(missingDatabaseName));
            var migrationService = new JellyfinMigrationService(
                factory.Object,
                NullLoggerFactory.Instance,
                new StartupLogger<JellyfinMigrationService>(NullLogger<JellyfinMigrationService>.Instance),
                paths,
                jellyfinDatabaseProvider: provider);

            var exception = await Assert.ThrowsAsync<InvalidOperationException>(
                () => migrationService.CheckFirstTimeRunOrMigration(paths, new StartupOptions())).ConfigureAwait(true);

            Assert.Contains("Create the configured database", exception.Message, StringComparison.Ordinal);
            Assert.Contains("does not require or use PostgreSQL CREATEDB", exception.Message, StringComparison.Ordinal);
            Assert.False(await _fixture.DatabaseExistsAsync(missingDatabaseName, cancellationToken).ConfigureAwait(true));
        }
        finally
        {
            Directory.Delete(root, true);
        }
    }

    [Fact]
    public async Task Baseline_CreatesCriticalPostgreSqlCatalogObjects()
    {
        Assert.SkipUnless(_fixture.IsConfigured, _fixture.SkipReason);
        var cancellationToken = TestContext.Current.CancellationToken;
        var database = await _fixture.GetDatabaseAsync(cancellationToken).ConfigureAwait(true);
        await database.ResetAsync(cancellationToken).ConfigureAwait(true);

        await using (var context = database.CreateDbContext())
        {
            await context.Database.MigrateAsync(cancellationToken).ConfigureAwait(true);
        }

        Assert.Equal(
            8,
            await database.ExecuteScalarAsync<long>(
                """
                SELECT count(*)
                FROM pg_tables
                WHERE schemaname = 'public'
                    AND tablename IN (
                        'ActivityLogs',
                        'BaseItems',
                        'BaseItemProviders',
                        'CustomItemDisplayPreferences',
                        'ItemValues',
                        'Peoples',
                        'Users',
                        '__EFMigrationsHistory')
                """,
                cancellationToken).ConfigureAwait(true));
        Assert.Equal(
            "YES",
            await database.ExecuteScalarAsync<string>(
                "SELECT is_identity FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'ActivityLogs' AND column_name = 'Id'",
                cancellationToken).ConfigureAwait(true));
        Assert.Equal(
            "BY DEFAULT",
            await database.ExecuteScalarAsync<string>(
                "SELECT identity_generation FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'ActivityLogs' AND column_name = 'Id'",
                cancellationToken).ConfigureAwait(true));
        Assert.Equal(
            "timestamp with time zone",
            await database.ExecuteScalarAsync<string>(
                "SELECT data_type FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'ActivityLogs' AND column_name = 'DateCreated'",
                cancellationToken).ConfigureAwait(true));
        Assert.Equal(
            "bytea",
            await database.ExecuteScalarAsync<string>(
                "SELECT data_type FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'ItemValues' AND column_name = 'ValueDigest'",
                cancellationToken).ConfigureAwait(true));
        Assert.Equal(
            "ARRAY",
            await database.ExecuteScalarAsync<string>(
                "SELECT data_type FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'KeyframeData' AND column_name = 'KeyframeTicks'",
                cancellationToken).ConfigureAwait(true));
        Assert.Equal(
            "C",
            await database.ExecuteScalarAsync<string>(
                "SELECT collation_name FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'Peoples' AND column_name = 'Name'",
                cancellationToken).ConfigureAwait(true));
        Assert.Equal(
            "ALWAYS",
            await database.ExecuteScalarAsync<string>(
                "SELECT is_generated FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'Peoples' AND column_name = 'NameLower'",
                cancellationToken).ConfigureAwait(true));
        Assert.Contains(
            "lower(\"Name\")",
            await database.ExecuteScalarAsync<string>(
                "SELECT generation_expression FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'Peoples' AND column_name = 'NameLower'",
                cancellationToken).ConfigureAwait(true),
            StringComparison.Ordinal);
        Assert.Contains(
            "USING hash",
            await database.ExecuteScalarAsync<string>(
                "SELECT indexdef FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'IX_Peoples_NameLower'",
                cancellationToken).ConfigureAwait(true),
            StringComparison.Ordinal);

        var partialIndex = await database.ExecuteScalarAsync<string>(
            "SELECT indexdef FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'IX_BaseItems_OwnerId'",
            cancellationToken).ConfigureAwait(true);
        Assert.Contains("WHERE", partialIndex, StringComparison.Ordinal);
        Assert.Contains("OwnerId", partialIndex, StringComparison.Ordinal);
        Assert.Contains(
            "PrimaryVersionId",
            await database.ExecuteScalarAsync<string>(
                "SELECT indexdef FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'IX_BaseItems_TopParentId_Type_IsVirtualItem'",
                cancellationToken).ConfigureAwait(true),
            StringComparison.Ordinal);

        Assert.Equal(
            "ItemId,ProviderIdDigest",
            await database.ExecuteScalarAsync<string>(
                """
                SELECT string_agg(attribute.attname, ',' ORDER BY array_position(constraint_record.conkey, attribute.attnum))
                FROM pg_constraint AS constraint_record
                JOIN pg_class AS table_record ON table_record.oid = constraint_record.conrelid
                JOIN pg_namespace AS namespace_record ON namespace_record.oid = table_record.relnamespace
                JOIN pg_attribute AS attribute
                    ON attribute.attrelid = table_record.oid
                    AND attribute.attnum = ANY(constraint_record.conkey)
                WHERE namespace_record.nspname = 'public'
                    AND table_record.relname = 'BaseItemProviders'
                    AND constraint_record.contype = 'p'
                """,
                cancellationToken).ConfigureAwait(true));
        Assert.Equal(
            "ItemId,PeopleId,RoleDigest",
            await GetPrimaryKeyColumnsAsync(database, "PeopleBaseItemMap", cancellationToken).ConfigureAwait(true));
        Assert.Equal(
            "ItemId,UserId,CustomDataKeyDigest",
            await GetPrimaryKeyColumnsAsync(database, "UserData", cancellationToken).ConfigureAwait(true));
        Assert.Equal(
            "NO",
            await database.ExecuteScalarAsync<string>(
                "SELECT is_nullable FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'BaseItemProviders' AND column_name = 'ProviderId'",
                cancellationToken).ConfigureAwait(true));
        Assert.Equal(
            "NO",
            await database.ExecuteScalarAsync<string>(
                "SELECT is_nullable FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'PeopleBaseItemMap' AND column_name = 'Role'",
                cancellationToken).ConfigureAwait(true));
        Assert.Equal(
            "NO",
            await database.ExecuteScalarAsync<string>(
                "SELECT is_nullable FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'UserData' AND column_name = 'CustomDataKey'",
                cancellationToken).ConfigureAwait(true));
        Assert.Equal(
            "bytea",
            await database.ExecuteScalarAsync<string>(
                "SELECT data_type FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'PeopleBaseItemMap' AND column_name = 'RoleDigest'",
                cancellationToken).ConfigureAwait(true));
        Assert.Equal(
            "bytea",
            await database.ExecuteScalarAsync<string>(
                "SELECT data_type FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'UserData' AND column_name = 'CustomDataKeyDigest'",
                cancellationToken).ConfigureAwait(true));
        Assert.Contains(
            "UNIQUE",
            await database.ExecuteScalarAsync<string>(
                "SELECT indexdef FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'IX_ItemValues_Type_ValueDigest'",
                cancellationToken).ConfigureAwait(true),
            StringComparison.Ordinal);
        Assert.Equal(
            "CASCADE",
            await database.ExecuteScalarAsync<string>(
                "SELECT delete_rule FROM information_schema.referential_constraints WHERE constraint_name = 'FK_BaseItems_BaseItems_ParentId'",
                cancellationToken).ConfigureAwait(true));
        Assert.Equal(
            "NO ACTION",
            await database.ExecuteScalarAsync<string>(
                "SELECT delete_rule FROM information_schema.referential_constraints WHERE constraint_name = 'FK_BaseItems_BaseItems_OwnerId'",
                cancellationToken).ConfigureAwait(true));
        Assert.Equal(
            0,
            await database.ExecuteScalarAsync<long>(
                "SELECT count(*) FROM information_schema.columns WHERE table_schema = 'public' AND column_default IS NOT NULL AND is_identity = 'NO'",
                cancellationToken).ConfigureAwait(true));
        Assert.True(
            await database.ExecuteScalarAsync<bool>(
                "SELECT EXISTS (SELECT 1 FROM \"BaseItems\" WHERE \"Id\" = '00000000-0000-0000-0000-000000000001' AND \"Type\" = 'PLACEHOLDER')",
                cancellationToken).ConfigureAwait(true));
        Assert.InRange(
            await database.ExecuteScalarAsync<int>(
                """
                SELECT max(length(object_name))
                FROM (
                    SELECT class_record.relname AS object_name
                    FROM pg_class AS class_record
                    JOIN pg_namespace AS namespace_record ON namespace_record.oid = class_record.relnamespace
                    WHERE namespace_record.nspname = 'public'
                    UNION ALL
                    SELECT constraint_record.conname
                    FROM pg_constraint AS constraint_record
                    JOIN pg_namespace AS namespace_record ON namespace_record.oid = constraint_record.connamespace
                    WHERE namespace_record.nspname = 'public'
                ) AS schema_objects
                """,
                cancellationToken).ConfigureAwait(true),
            1,
            63);
    }

    [Fact]
    public async Task Baseline_IdentityAndCascadeRelationshipBehaveCorrectly()
    {
        Assert.SkipUnless(_fixture.IsConfigured, _fixture.SkipReason);
        var cancellationToken = TestContext.Current.CancellationToken;
        var database = await _fixture.GetDatabaseAsync(cancellationToken).ConfigureAwait(true);
        await database.ResetAsync(cancellationToken).ConfigureAwait(true);
        var parentId = Guid.NewGuid();
        var childId = Guid.NewGuid();

        await using (var context = database.CreateDbContext())
        {
            await context.Database.MigrateAsync(cancellationToken).ConfigureAwait(true);
            var activity = new ActivityLog("migration identity", "MigrationTest", Guid.NewGuid());
            var parent = new BaseItemEntity { Id = parentId, Type = "Folder", IsFolder = true };
            var child = new BaseItemEntity { Id = childId, Type = "Movie", ParentId = parentId };
            context.ActivityLogs.Add(activity);
            context.BaseItems.AddRange(parent, child);

            await context.SaveChangesAsync(cancellationToken).ConfigureAwait(true);

            Assert.True(activity.Id > 0);
        }

        await using (var context = database.CreateDbContext())
        {
            context.BaseItems.Remove(new BaseItemEntity { Id = parentId, Type = "Folder" });
            await context.SaveChangesAsync(cancellationToken).ConfigureAwait(true);
        }

        await using (var context = database.CreateDbContext())
        {
            Assert.False(await context.BaseItems.AnyAsync(item => item.Id.Equals(childId), cancellationToken).ConfigureAwait(true));
        }
    }

    [Fact]
    public async Task StripEmbeddedLinkedChildren_UsesPortableTransformOnPostgreSql()
    {
        Assert.SkipUnless(_fixture.IsConfigured, _fixture.SkipReason);
        var cancellationToken = TestContext.Current.CancellationToken;
        var database = await _fixture.GetDatabaseAsync(cancellationToken).ConfigureAwait(true);
        await database.ResetAsync(cancellationToken).ConfigureAwait(true);
        var migratedId = Guid.NewGuid();
        var malformedId = Guid.NewGuid();
        const string MalformedData = "{\"LinkedChildren\":";

        await using (var context = database.CreateDbContext())
        {
            await context.Database.MigrateAsync(cancellationToken).ConfigureAwait(true);
            context.BaseItems.AddRange(
                new BaseItemEntity
                {
                    Id = migratedId,
                    Type = "Movie",
                    Data = "{\"Name\":\"kept\",\"LinkedChildren\":[1],\"ExtraIds\":{},\"SupportsExternalTransfer\":true}"
                },
                new BaseItemEntity { Id = malformedId, Type = "Movie", Data = MalformedData });
            await context.SaveChangesAsync(cancellationToken).ConfigureAwait(true);
        }

        var factory = new Mock<IDbContextFactory<JellyfinDbContext>>();
        factory
            .Setup(contextFactory => contextFactory.CreateDbContextAsync(It.IsAny<CancellationToken>()))
            .ReturnsAsync(database.CreateDbContext);
        await new StripEmbeddedLinkedChildren(NullLoggerFactory.Instance, factory.Object)
            .PerformAsync(cancellationToken)
            .ConfigureAwait(true);

        await using var verification = database.CreateDbContext();
        var migrated = JsonNode.Parse((await verification.BaseItems.FindAsync([migratedId], cancellationToken).ConfigureAwait(true))!.Data!)!.AsObject();
        Assert.Equal("kept", migrated["Name"]!.GetValue<string>());
        Assert.False(migrated.ContainsKey("LinkedChildren"));
        Assert.False(migrated.ContainsKey("ExtraIds"));
        Assert.False(migrated.ContainsKey("SupportsExternalTransfer"));
        Assert.Equal(
            MalformedData,
            (await verification.BaseItems.FindAsync([malformedId], cancellationToken).ConfigureAwait(true))!.Data);
    }

    [Fact]
    public async Task NoLock_AllowsIndependentConcurrentWritesOnPostgreSql()
    {
        Assert.SkipUnless(_fixture.IsConfigured, _fixture.SkipReason);
        var cancellationToken = TestContext.Current.CancellationToken;
        var database = await _fixture.GetDatabaseAsync(cancellationToken).ConfigureAwait(true);
        await database.ResetAsync(cancellationToken).ConfigureAwait(true);

        await using (var context = database.CreateDbContext())
        {
            await context.Database.MigrateAsync(cancellationToken).ConfigureAwait(true);
        }

        var ids = Enumerable.Range(0, 32).Select(_ => Guid.NewGuid()).ToArray();
        await Task.WhenAll(ids.Select(async id =>
        {
            await using var context = database.CreateDbContext();
            context.BaseItems.Add(new BaseItemEntity { Id = id, Type = "Movie" });
            await context.SaveChangesAsync(cancellationToken).ConfigureAwait(false);
        })).ConfigureAwait(true);

        await using var verification = database.CreateDbContext();
        Assert.Equal(32, await verification.BaseItems.CountAsync(item => ids.Contains(item.Id), cancellationToken).ConfigureAwait(true));
    }

    private static ServerApplicationPaths CreateApplicationPaths(string root)
    {
        var paths = new ServerApplicationPaths(
            Path.Combine(root, "data"),
            Path.Combine(root, "log"),
            Path.Combine(root, "config"),
            Path.Combine(root, "cache"),
            Path.Combine(root, "web"));
        Directory.CreateDirectory(paths.DataPath);
        Directory.CreateDirectory(paths.LogDirectoryPath);
        Directory.CreateDirectory(paths.ConfigurationDirectoryPath);
        Directory.CreateDirectory(paths.CachePath);
        return paths;
    }

    [Fact]
    public async Task Baseline_UnboundedCompositeTextKeysSupportExactCrudAndUniqueness()
    {
        Assert.SkipUnless(_fixture.IsConfigured, _fixture.SkipReason);
        var cancellationToken = TestContext.Current.CancellationToken;
        var database = await _fixture.GetDatabaseAsync(cancellationToken).ConfigureAwait(true);
        await database.ResetAsync(cancellationToken).ConfigureAwait(true);

        var itemId = Guid.NewGuid();
        var peopleId = Guid.NewGuid();
        var rolePrefix = new string('r', 4_000);
        var role = rolePrefix + "-first";
        var distinctRole = rolePrefix + "-second";
        var keyPrefix = new string('k', 12_000);
        var customDataKey = keyPrefix + "-first";
        var distinctCustomDataKey = keyPrefix + "-second";
        Guid userId;

        await using (var context = database.CreateDbContext())
        {
            await context.Database.MigrateAsync(cancellationToken).ConfigureAwait(true);
            var item = new BaseItemEntity { Id = itemId, Type = "Movie" };
            var person = new People { Id = peopleId, Name = "Long Role", PersonType = "Actor" };
            var user = new User("long-composite-keys", "test-auth", "test-reset");
            userId = user.Id;
            var firstMap = new PeopleBaseItemMap
            {
                ItemId = itemId,
                Item = item,
                PeopleId = peopleId,
                People = person,
                Role = "temporary",
                SortOrder = 1
            };
            firstMap.Role = role;
            var firstUserData = new UserData
            {
                ItemId = itemId,
                Item = item,
                UserId = userId,
                User = user,
                CustomDataKey = "temporary",
                PlayCount = 1
            };
            firstUserData.CustomDataKey = customDataKey;

            context.BaseItems.Add(item);
            context.Peoples.Add(person);
            context.Users.Add(user);
            context.PeopleBaseItemMap.AddRange(
                firstMap,
                new PeopleBaseItemMap
                {
                    ItemId = itemId,
                    Item = item,
                    PeopleId = peopleId,
                    People = person,
                    Role = distinctRole,
                    SortOrder = 10
                });
            context.UserData.AddRange(
                firstUserData,
                new UserData
                {
                    ItemId = itemId,
                    Item = item,
                    UserId = userId,
                    User = user,
                    CustomDataKey = distinctCustomDataKey,
                    PlayCount = 10
                });

            await context.SaveChangesAsync(cancellationToken).ConfigureAwait(true);
        }

        await using (var context = database.CreateDbContext())
        {
            var storedMap = await context.PeopleBaseItemMap.SingleAsync(map => map.Role == role, cancellationToken).ConfigureAwait(true);
            var storedUserData = await context.UserData.SingleAsync(data => data.CustomDataKey == customDataKey, cancellationToken).ConfigureAwait(true);
            Assert.Equal(role, storedMap.Role);
            Assert.Equal(SHA256.HashData(Encoding.UTF8.GetBytes(role)), storedMap.RoleDigest);
            Assert.Equal(customDataKey, storedUserData.CustomDataKey);
            Assert.Equal(SHA256.HashData(Encoding.UTF8.GetBytes(customDataKey)), storedUserData.CustomDataKeyDigest);
            Assert.Equal(2, await context.PeopleBaseItemMap.CountAsync(cancellationToken).ConfigureAwait(true));
            Assert.Equal(2, await context.UserData.CountAsync(data => data.UserId.Equals(userId), cancellationToken).ConfigureAwait(true));

            storedMap.SortOrder = 2;
            storedUserData.PlayCount = 2;
            await context.SaveChangesAsync(cancellationToken).ConfigureAwait(true);
        }

        await using (var duplicateMapContext = database.CreateDbContext())
        {
            duplicateMapContext.PeopleBaseItemMap.Add(new PeopleBaseItemMap
            {
                ItemId = itemId,
                Item = null!,
                PeopleId = peopleId,
                People = null!,
                Role = role
            });
            await Assert.ThrowsAsync<DbUpdateException>(
                () => duplicateMapContext.SaveChangesAsync(cancellationToken)).ConfigureAwait(true);
        }

        await using (var duplicateUserDataContext = database.CreateDbContext())
        {
            duplicateUserDataContext.UserData.Add(new UserData
            {
                ItemId = itemId,
                Item = null!,
                UserId = userId,
                User = null!,
                CustomDataKey = customDataKey
            });
            await Assert.ThrowsAsync<DbUpdateException>(
                () => duplicateUserDataContext.SaveChangesAsync(cancellationToken)).ConfigureAwait(true);
        }

        await using (var context = database.CreateDbContext())
        {
            var storedMap = await context.PeopleBaseItemMap.SingleAsync(map => map.Role == role, cancellationToken).ConfigureAwait(true);
            var storedUserData = await context.UserData.SingleAsync(data => data.CustomDataKey == customDataKey, cancellationToken).ConfigureAwait(true);
            Assert.Equal(2, storedMap.SortOrder);
            Assert.Equal(2, storedUserData.PlayCount);
            context.PeopleBaseItemMap.Remove(storedMap);
            context.UserData.Remove(storedUserData);
            await context.SaveChangesAsync(cancellationToken).ConfigureAwait(true);
        }

        await using (var context = database.CreateDbContext())
        {
            Assert.False(await context.PeopleBaseItemMap.AnyAsync(map => map.Role == role, cancellationToken).ConfigureAwait(true));
            Assert.True(await context.PeopleBaseItemMap.AnyAsync(map => map.Role == distinctRole, cancellationToken).ConfigureAwait(true));
            Assert.False(await context.UserData.AnyAsync(data => data.CustomDataKey == customDataKey, cancellationToken).ConfigureAwait(true));
            Assert.True(await context.UserData.AnyAsync(data => data.CustomDataKey == distinctCustomDataKey, cancellationToken).ConfigureAwait(true));
        }
    }

    private static Task<string> GetPrimaryKeyColumnsAsync(
        PostgreSqlTestDatabase database,
        string tableName,
        CancellationToken cancellationToken)
        => database.ExecuteScalarAsync<string>(
            $"""
            SELECT string_agg(attribute.attname, ',' ORDER BY array_position(constraint_record.conkey, attribute.attnum))
            FROM pg_constraint AS constraint_record
            JOIN pg_class AS table_record ON table_record.oid = constraint_record.conrelid
            JOIN pg_namespace AS namespace_record ON namespace_record.oid = table_record.relnamespace
            JOIN pg_attribute AS attribute
                ON attribute.attrelid = table_record.oid
                AND attribute.attnum = ANY(constraint_record.conkey)
            WHERE namespace_record.nspname = 'public'
                AND table_record.relname = '{tableName}'
                AND constraint_record.contype = 'p'
            """,
            cancellationToken);
}
