using System;
using System.Linq;
using System.Threading.Tasks;
using Jellyfin.Database.Implementations.Entities;
using Jellyfin.Database.Providers.PostgreSql.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Xunit;

namespace Jellyfin.Server.Implementations.Tests.Data.PostgreSql;

[Collection(PostgreSqlIntegrationCollection.Name)]
public sealed class PostgreSqlMigrationTests
{
    private readonly PostgreSqlDatabaseFixture _fixture;

    public PostgreSqlMigrationTests(PostgreSqlDatabaseFixture fixture)
    {
        _fixture = fixture;
    }

    [Fact]
    public void MigrationAssembly_HasIndependentBaselineAndGeneratesIdempotentScript()
    {
        var factory = new PostgreSqlDesignTimeJellyfinDbFactory();
        using var context = factory.CreateDbContext([]);
        var baseline = Assert.Single(context.Database.GetMigrations());

        Assert.EndsWith("_InitialPostgreSqlBaseline", baseline, StringComparison.Ordinal);
        Assert.DoesNotContain("SQLite", baseline, StringComparison.OrdinalIgnoreCase);

        var script = context.GetService<IMigrator>().GenerateScript(
            Migration.InitialDatabase,
            baseline,
            MigrationsSqlGenerationOptions.Idempotent);

        Assert.Contains("CREATE TABLE IF NOT EXISTS \"__EFMigrationsHistory\"", script, StringComparison.Ordinal);
        Assert.Contains($"WHERE \"MigrationId\" = '{baseline}'", script, StringComparison.Ordinal);
        Assert.Contains("GENERATED BY DEFAULT AS IDENTITY", script, StringComparison.Ordinal);
        Assert.Contains("GENERATED ALWAYS AS (lower(\"Name\")) STORED", script, StringComparison.Ordinal);
        Assert.Contains("USING hash", script, StringComparison.Ordinal);
        Assert.DoesNotContain("PRAGMA", script, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public async Task MigrateAsync_AppliesBaselineOnceAndCanRunAgain()
    {
        Assert.SkipUnless(_fixture.IsConfigured, _fixture.SkipReason);
        var cancellationToken = TestContext.Current.CancellationToken;
        var database = await _fixture.GetDatabaseAsync(cancellationToken).ConfigureAwait(true);
        await database.ResetAsync(cancellationToken).ConfigureAwait(true);

        string baseline;
        await using (var context = database.CreateDbContext())
        {
            baseline = Assert.Single(context.Database.GetMigrations());
            await context.Database.MigrateAsync(cancellationToken).ConfigureAwait(true);

            Assert.Empty(await context.Database.GetPendingMigrationsAsync(cancellationToken).ConfigureAwait(true));
            Assert.Equal(new[] { baseline }, await context.Database.GetAppliedMigrationsAsync(cancellationToken).ConfigureAwait(true));
        }

        await using (var context = database.CreateDbContext())
        {
            await context.Database.MigrateAsync(cancellationToken).ConfigureAwait(true);

            Assert.Empty(await context.Database.GetPendingMigrationsAsync(cancellationToken).ConfigureAwait(true));
            Assert.Equal(new[] { baseline }, await context.Database.GetAppliedMigrationsAsync(cancellationToken).ConfigureAwait(true));
        }

        Assert.Equal(
            1,
            await database.ExecuteScalarAsync<long>(
                "SELECT count(*) FROM \"__EFMigrationsHistory\"",
                cancellationToken).ConfigureAwait(true));
    }

    [Fact]
    public async Task Baseline_CreatesCriticalPostgreSqlCatalogObjects()
    {
        Assert.SkipUnless(_fixture.IsConfigured, _fixture.SkipReason);
        var cancellationToken = TestContext.Current.CancellationToken;
        var database = await _fixture.GetDatabaseAsync(cancellationToken).ConfigureAwait(true);
        await database.ResetAsync(cancellationToken).ConfigureAwait(true);

        await using (var context = database.CreateDbContext())
        {
            await context.Database.MigrateAsync(cancellationToken).ConfigureAwait(true);
        }

        Assert.Equal(
            8,
            await database.ExecuteScalarAsync<long>(
                """
                SELECT count(*)
                FROM pg_tables
                WHERE schemaname = 'public'
                    AND tablename IN (
                        'ActivityLogs',
                        'BaseItems',
                        'BaseItemProviders',
                        'CustomItemDisplayPreferences',
                        'ItemValues',
                        'Peoples',
                        'Users',
                        '__EFMigrationsHistory')
                """,
                cancellationToken).ConfigureAwait(true));
        Assert.Equal(
            "YES",
            await database.ExecuteScalarAsync<string>(
                "SELECT is_identity FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'ActivityLogs' AND column_name = 'Id'",
                cancellationToken).ConfigureAwait(true));
        Assert.Equal(
            "BY DEFAULT",
            await database.ExecuteScalarAsync<string>(
                "SELECT identity_generation FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'ActivityLogs' AND column_name = 'Id'",
                cancellationToken).ConfigureAwait(true));
        Assert.Equal(
            "timestamp with time zone",
            await database.ExecuteScalarAsync<string>(
                "SELECT data_type FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'ActivityLogs' AND column_name = 'DateCreated'",
                cancellationToken).ConfigureAwait(true));
        Assert.Equal(
            "bytea",
            await database.ExecuteScalarAsync<string>(
                "SELECT data_type FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'ItemValues' AND column_name = 'ValueDigest'",
                cancellationToken).ConfigureAwait(true));
        Assert.Equal(
            "ARRAY",
            await database.ExecuteScalarAsync<string>(
                "SELECT data_type FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'KeyframeData' AND column_name = 'KeyframeTicks'",
                cancellationToken).ConfigureAwait(true));
        Assert.Equal(
            "C",
            await database.ExecuteScalarAsync<string>(
                "SELECT collation_name FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'Peoples' AND column_name = 'Name'",
                cancellationToken).ConfigureAwait(true));
        Assert.Equal(
            "ALWAYS",
            await database.ExecuteScalarAsync<string>(
                "SELECT is_generated FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'Peoples' AND column_name = 'NameLower'",
                cancellationToken).ConfigureAwait(true));
        Assert.Contains(
            "lower(\"Name\")",
            await database.ExecuteScalarAsync<string>(
                "SELECT generation_expression FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'Peoples' AND column_name = 'NameLower'",
                cancellationToken).ConfigureAwait(true),
            StringComparison.Ordinal);
        Assert.Contains(
            "USING hash",
            await database.ExecuteScalarAsync<string>(
                "SELECT indexdef FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'IX_Peoples_NameLower'",
                cancellationToken).ConfigureAwait(true),
            StringComparison.Ordinal);

        var partialIndex = await database.ExecuteScalarAsync<string>(
            "SELECT indexdef FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'IX_BaseItems_OwnerId'",
            cancellationToken).ConfigureAwait(true);
        Assert.Contains("WHERE", partialIndex, StringComparison.Ordinal);
        Assert.Contains("OwnerId", partialIndex, StringComparison.Ordinal);
        Assert.Contains(
            "PrimaryVersionId",
            await database.ExecuteScalarAsync<string>(
                "SELECT indexdef FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'IX_BaseItems_TopParentId_Type_IsVirtualItem'",
                cancellationToken).ConfigureAwait(true),
            StringComparison.Ordinal);

        Assert.Equal(
            "ItemId,ProviderIdDigest",
            await database.ExecuteScalarAsync<string>(
                """
                SELECT string_agg(attribute.attname, ',' ORDER BY array_position(constraint_record.conkey, attribute.attnum))
                FROM pg_constraint AS constraint_record
                JOIN pg_class AS table_record ON table_record.oid = constraint_record.conrelid
                JOIN pg_namespace AS namespace_record ON namespace_record.oid = table_record.relnamespace
                JOIN pg_attribute AS attribute
                    ON attribute.attrelid = table_record.oid
                    AND attribute.attnum = ANY(constraint_record.conkey)
                WHERE namespace_record.nspname = 'public'
                    AND table_record.relname = 'BaseItemProviders'
                    AND constraint_record.contype = 'p'
                """,
                cancellationToken).ConfigureAwait(true));
        Assert.Contains(
            "UNIQUE",
            await database.ExecuteScalarAsync<string>(
                "SELECT indexdef FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'IX_ItemValues_Type_ValueDigest'",
                cancellationToken).ConfigureAwait(true),
            StringComparison.Ordinal);
        Assert.Equal(
            "CASCADE",
            await database.ExecuteScalarAsync<string>(
                "SELECT delete_rule FROM information_schema.referential_constraints WHERE constraint_name = 'FK_BaseItems_BaseItems_ParentId'",
                cancellationToken).ConfigureAwait(true));
        Assert.Equal(
            "NO ACTION",
            await database.ExecuteScalarAsync<string>(
                "SELECT delete_rule FROM information_schema.referential_constraints WHERE constraint_name = 'FK_BaseItems_BaseItems_OwnerId'",
                cancellationToken).ConfigureAwait(true));
        Assert.Equal(
            0,
            await database.ExecuteScalarAsync<long>(
                "SELECT count(*) FROM information_schema.columns WHERE table_schema = 'public' AND column_default IS NOT NULL AND is_identity = 'NO'",
                cancellationToken).ConfigureAwait(true));
        Assert.True(
            await database.ExecuteScalarAsync<bool>(
                "SELECT EXISTS (SELECT 1 FROM \"BaseItems\" WHERE \"Id\" = '00000000-0000-0000-0000-000000000001' AND \"Type\" = 'PLACEHOLDER')",
                cancellationToken).ConfigureAwait(true));
        Assert.InRange(
            await database.ExecuteScalarAsync<int>(
                """
                SELECT max(length(object_name))
                FROM (
                    SELECT class_record.relname AS object_name
                    FROM pg_class AS class_record
                    JOIN pg_namespace AS namespace_record ON namespace_record.oid = class_record.relnamespace
                    WHERE namespace_record.nspname = 'public'
                    UNION ALL
                    SELECT constraint_record.conname
                    FROM pg_constraint AS constraint_record
                    JOIN pg_namespace AS namespace_record ON namespace_record.oid = constraint_record.connamespace
                    WHERE namespace_record.nspname = 'public'
                ) AS schema_objects
                """,
                cancellationToken).ConfigureAwait(true),
            1,
            63);
    }

    [Fact]
    public async Task Baseline_IdentityAndCascadeRelationshipBehaveCorrectly()
    {
        Assert.SkipUnless(_fixture.IsConfigured, _fixture.SkipReason);
        var cancellationToken = TestContext.Current.CancellationToken;
        var database = await _fixture.GetDatabaseAsync(cancellationToken).ConfigureAwait(true);
        await database.ResetAsync(cancellationToken).ConfigureAwait(true);
        var parentId = Guid.NewGuid();
        var childId = Guid.NewGuid();

        await using (var context = database.CreateDbContext())
        {
            await context.Database.MigrateAsync(cancellationToken).ConfigureAwait(true);
            var activity = new ActivityLog("migration identity", "MigrationTest", Guid.NewGuid());
            var parent = new BaseItemEntity { Id = parentId, Type = "Folder", IsFolder = true };
            var child = new BaseItemEntity { Id = childId, Type = "Movie", ParentId = parentId };
            context.ActivityLogs.Add(activity);
            context.BaseItems.AddRange(parent, child);

            await context.SaveChangesAsync(cancellationToken).ConfigureAwait(true);

            Assert.True(activity.Id > 0);
        }

        await using (var context = database.CreateDbContext())
        {
            context.BaseItems.Remove(new BaseItemEntity { Id = parentId, Type = "Folder" });
            await context.SaveChangesAsync(cancellationToken).ConfigureAwait(true);
        }

        await using (var context = database.CreateDbContext())
        {
            Assert.False(await context.BaseItems.AnyAsync(item => item.Id.Equals(childId), cancellationToken).ConfigureAwait(true));
        }
    }
}
